apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    app: sample-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgresDB-app-pod
    app: sample-voting-app # does not have to be same name as metadata above                                                       
