apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: sample-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-app-pod
    app: sample-voting-app # does not have to be same name as metadata above                                                                          
