apiVersion: v1
kind: Pod
metadata:
  name: postgresdb-app-pod
  labels:
    name: postgresDB-app-pod #note that the label does not have be same name as the metadata
    app: sample-voting-app
spec:
  containers:
     - name: postgresdb-app-container
       image: postgres:9.4
       ports:
         - containerPort: 5432
       env:
         - name: POSTGRES_USER
           value: "postgres"
         - name: POSTGRES_PASSWORD
           value: "postgres"
