apiVersion: v1
kind: Pod
metadata:
  name: redis-app-pod
  labels:
    name: redis-app-pod #note that the label does not have be same name as the metadata
    app: sample-voting-app
spec:
  containers:
     - name: redis-app-container
       image: redis
       ports:
         - containerPort: 6379
