apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod #note that the label does not have be same name as the metadata
    app: sample-voting-app
spec:
  containers:
     - name: voting-app-container
       image: kodekloud/examplevotingapp_vote:v1
       ports:
         - containerPort: 80
       

