apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - service.yaml
  - deployment.yaml

labels:
  - pairs:
      app: my-web-app
      owner: Maryam
    includeSelectors: true

namePrefix: kustomize-
