apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2 # Update the replica count to 2
  template:
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            cpu: "150m" # set 0.15 cpu core for Pod
            memory: "120Mi" # Lower memory limit to 512 MiB
          requests:
            cpu: "100m" # Lower CPU request to 2000m (2 CPU core)
            memory: "80Mi" # Lower memory request to 128 MiB
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
