# using the Deployment object to create multiple pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app-deployment
  labels:
    name: postgres-app-deployment # note that the label does not have be same name as the metadata
    app: sample-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresDB-app-pod # note that the label does not have be same name as the metadata
      app: sample-voting-app
  template:
    metadata:
      name: postgresdb-app-pod
      labels:
        name: postgresDB-app-pod #note that the label does not have be same name as the metadata
        app: sample-voting-app
    spec:
      containers:
        - name: postgresdb-app-container
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
