apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: mongo-service # this must have the same value as specified for the 'name' in the metaadata section of the database 'service' yaml configuration manifest
